base:
    is_dev: false
db_info:
    host: 192.168.33.10
    port: 3306
    username: root
    password: 123.com
    database: pluvia
    type: 0
out_dir: ./models
url_tag: json
language: 中 文
db_tag: gorm
user_gorm_model: false
simple: false
is_web_tag: true
is_web_tag_pk_hidden: false
is_foreign_key: true
is_out_sql: false
is_out_func: false
is_gui: true
is_table_name: true
is_null_to_point: false
is_null_to_sql_null: false
table_prefix: ""
self_type_define:
    time: calendar.Time
    date: calendar.Date
    datetime: calendar.Datetime
out_file_name: ""
web_tag_type: 0
table_names: ""
is_column_name: false
is_out_file_by_table_name: false
is_out_page: false

